// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg0YzL_puoGskm5d_t9M_oDlJA7bEGhpY',
    appId: '1:346096042374:web:abca9e0dbedcd1def16c07',
    messagingSenderId: '346096042374',
    projectId: 'roadsafe-ai-c6800',
    authDomain: 'roadsafe-ai-c6800.firebaseapp.com',
    storageBucket: 'roadsafe-ai-c6800.firebasestorage.app',
    measurementId: 'G-JGHK0G1PJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSgsNgjscEE7iIIZeNDiZ8k-kfiUJBB5k',
    appId: '1:346096042374:android:34367af7745aa707f16c07',
    messagingSenderId: '346096042374',
    projectId: 'roadsafe-ai-c6800',
    storageBucket: 'roadsafe-ai-c6800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd8CyyYz9eTJ2LyTu_ftxyXK97bv3nc40',
    appId: '1:346096042374:ios:c6e5de17fba3991ff16c07',
    messagingSenderId: '346096042374',
    projectId: 'roadsafe-ai-c6800',
    storageBucket: 'roadsafe-ai-c6800.firebasestorage.app',
    iosBundleId: 'com.example.roadSafeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd8CyyYz9eTJ2LyTu_ftxyXK97bv3nc40',
    appId: '1:346096042374:ios:c6e5de17fba3991ff16c07',
    messagingSenderId: '346096042374',
    projectId: 'roadsafe-ai-c6800',
    storageBucket: 'roadsafe-ai-c6800.firebasestorage.app',
    iosBundleId: 'com.example.roadSafeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg0YzL_puoGskm5d_t9M_oDlJA7bEGhpY',
    appId: '1:346096042374:web:3251c279f3402092f16c07',
    messagingSenderId: '346096042374',
    projectId: 'roadsafe-ai-c6800',
    authDomain: 'roadsafe-ai-c6800.firebaseapp.com',
    storageBucket: 'roadsafe-ai-c6800.firebasestorage.app',
    measurementId: 'G-7GLC13VR1W',
  );
}
